Bugfixed/further cli functionality
aleph-im/aleph-client pull request #147
Opened 2023-02-03 22:45 UTC by AneequeZubair9

Fixed
Descriptions for the CLI parameters:
--allow-amend: Whether the deployed VM image may be changed and deployed on the same URL
--use-latest: Whether to use latest version of the base docker image
--reproducible: Not Implemented 
--internet: Whether the VM should have internet connectivity
--aleph_api: Whether the VM needs access to Aleph messages API

2023-02-07 17:37 UTC, MHHukiewitz requested changes
LGTM, minor changes required. Try to use https://black.readthedocs.io/en/stable/ to format all the modified files according to the style as the repository is formatted in

2023-02-07 17:37 UTC, MHHukiewitz commented on src/aleph_client/asynchronous.py
> +        api_server: str = settings.API_HOST,
Please use https://black.readthedocs.io/en/stable/ instead for auto-formatting code.

2023-02-07 17:37 UTC, MHHukiewitz commented on src/aleph_client/asynchronous.py
> +        aleph_api: bool,
You could assign default values here the same as the hardcoded ones before:
```suggestion
        aleph_api: bool = True,
```

2023-02-07 17:37 UTC, MHHukiewitz commented on src/aleph_client/commands/message.py
> +        debug: bool = False,
Same goes for formatting here

2023-02-07 17:37 UTC, MHHukiewitz commented on src/aleph_client/commands/program.py
> +        aleph_api: bool = typer.Option(True, help='VM needs access to Aleph messages AP'),
```suggestion
        aleph_api: bool = typer.Option(True, help='VM needs access to Aleph messages'),
```

2023-02-07 17:37 UTC, MHHukiewitz commented on tests/unit/test_asynchronous_get.py
> +    unittest.main()
Please revert changes here, we don't use `unittest`

2023-03-06 13:28 UTC, MHHukiewitz commented
Changes here need to be reimplemented in aleph-sdk-python. Closed.

2023-03-06 14:12 UTC, hoh commented
> Changes here need to be reimplemented in aleph-sdk-python. Closed.

Everything related to the CLI should be implemented in `aleph-client`, `aleph-sdk-python` is limited to libraries.

2023-11-13 16:14 UTC, closed without merging

2023-11-13 16:14 UTC, MHHukiewitz commented
Superseded by https://github.com/aleph-im/aleph-sdk-python/pull/77 and a future PR including the new parameters in the CLI.