Refactor: Migrate message commands to aleph-sdk-python #150
aleph-im/aleph-client pull request #163
Opened 2023-07-07 09:30 UTC by 1yam

From : https://github.com/aleph-im/aleph-client/pull/150

Refactor:

- Remove deprecated example of usage using mqtt.py.
- Fix mypy errors:
  - Replace typer.echo with typer.secho in account module.
  - Resolve type conversion errors in message module.
- Fix unit tests and integration tests.

2023-07-07 12:47 UTC, odesenfans requested changes

2023-07-07 12:47 UTC, odesenfans commented on tests/integration/itest_posts.py
> +        result, status = await client.create_post(
Rename result to message.

2023-07-07 12:47 UTC, odesenfans commented on tests/integration/itest_posts.py
> +        result, status = await client.create_post(
Also, now that the SDK returns a status, you can assert that the operation worked with `assert status == ...`.

2023-07-07 12:47 UTC, odesenfans commented on tests/integration/itest_posts.py
> +        timeout=50,
Why 50? Revert to 5, that's too long. Note that you can also specify `sync=True` in `client.create_post` to make sure that the message was processed on the API node.

2023-07-07 12:48 UTC, 1yam commented on src/aleph_client/commands/message.py
> +    content_types_s = content_types.split(",") if content_types else None
_s = _splited in my head

2023-07-07 19:20 UTC, 1yam commented on tests/integration/itest_posts.py
> +    data = {'content': 'test'}
Used here: https://github.com/1yam/aleph-client/blob/88843397a79658aa14bc4294d0f4c164a672661c/tests/integration/itest_posts.py#L31C9-L31C9

2023-07-09 22:01 UTC, odesenfans approved these changes

2023-07-10 08:29 UTC, merged