Feature: Cli download commands aleph & ipfs
aleph-im/aleph-client pull request #165
Opened 2023-07-11 09:57 UTC by 1yam

Solutions:
   - Create a new command that allows users to download a file from a hash.

2023-07-13 11:37 UTC, odesenfans requested changes

2023-07-13 11:37 UTC, odesenfans commented on src/aleph_client/commands/files.py
> +                file_content = client.download_file_ipfs(item_hash)
You can now use `download_file_to_buffer` to reduce memory usage.

2023-07-13 11:37 UTC, odesenfans commented on src/aleph_client/commands/utils.py
> +    file_path.write_bytes(content)
This function will be useless once you use `download_file_to_buffer`.

2023-11-09 10:38 UTC, MHHukiewitz requested changes
LGTM, only minor formating issues, use isort, flake8 & black

2023-11-09 10:38 UTC, MHHukiewitz commented on src/aleph_client/commands/utils.py
> +from pathlib import Path
unneeded import

2023-11-09 10:38 UTC, MHHukiewitz commented on src/aleph_client/commands/utils.py
> +
you can revert this file

2023-11-09 10:38 UTC, MHHukiewitz commented on tests/unit/test_utils.py
> +    assert get_message_type_value(ForgetMessage) == MessageType.forget
seems also unneeded? Maybe it's due to auto formatting

2023-11-10 15:08 UTC, MHHukiewitz commented on src/aleph_client/commands/files.py
> +    with AlephClient(api_server=sdk_settings.API_HOST) as client:
This is the wrong import, try using `async with AlephHttpClient`

2023-11-10 15:13 UTC, closed without merging

2023-11-10 15:13 UTC, MHHukiewitz commented
Closing this PR and will be superseded by a fresh branch. GH seems to not handle some of the rebases/force-pushes well that happened here