Refactor: instance list to handle PAYG instance
aleph-im/aleph-client pull request #215
Opened 2024-06-19 13:15 UTC by 1yam

Problem:
```aleph instance list``` only handles the Hold method.

Solution:
Check the payment type and fetch api_url and ipv6 from ```/about/executions/list.```

Changes:
- Added logic to check if there is a payment associated with the message.
- If there is no payment, the function fetches the VM details from the scheduler API.
- If there is a payment, the function fetches the server URL and retrieves the ipv6 address from the node's execution list

2024-06-27 11:25 UTC, Psycojoker commented
@1yam can you rebase this branch when you have some time plz? It conflicts with master now

2024-06-27 11:32 UTC, Psycojoker requested changes

2024-06-27 11:32 UTC, Psycojoker commented on src/aleph_client/commands/instance.py
> +async def _show_instances(messages: List[InstanceMessage], node_list):
Can you add some typing to `node_list` plz?

2024-06-27 11:32 UTC, Psycojoker commented on src/aleph_client/commands/instance.py
> +async def _get_ipv6_address(message: InstanceMessage, node_list) -> Tuple[str, str]:
Can you add some typing to `node_list` plz?

2024-06-28 16:06 UTC, 1yam commented
Clean PR : [](https://github.com/aleph-im/aleph-client/pull/224)

2024-06-28 16:06 UTC, closed without merging